### ISSUE TITLE
logs.txt no longer working with newer teams app

### ISSUE THREAD

**Issue by erSitzt** [jmpkc/BlinkStick-Microsoft-Teams-Status#2]
Hey Jason,

i was just starting to do the same, but with C#.
I hit a little bump, because it seems when switching to the new teams app, status messages are no longer logged..
Not sure how long the classic teams app will be available to use.. but it seems we need to find something else.

**Comment by jmpkc** [comment]
Oh, that's a good point.  I think I am using Teams Classic still.
Hmm.....  That's a bummer.  I'll have to think about that a bit more.
Thanks for the heads up!

**Comment by erSitzt** [comment]
a bit hacky... but this works in c#

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;


public class TeamsLogFile
{
    private const string statusIndicator = "UserPresenceAction:";
    public readonly string file;
    private string status;

    public TeamsLogFile(string file, TeamsLogFile previousLogFile = null)
    {
        this.file = file;
        status = null;
    }

    public string AnalyzeStatus(string line)
    {
        string statusResult = null;
        var resultStatus = Regex.Match(line, $@"^.*{{.*\bavailability\b:\s*([^\s,}}]*)");
        if (resultStatus.Success)
        {

            statusResult = resultStatus.Groups[1].Value;

        }
        return statusResult;
    }

    public string GetStatus()
    {
        using (var fs = new FileStream(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
        {
            using (var logFile = new StreamReader(fs))
            {
                string line;
                var indicatorLines = new List<string>();
                while ((line = logFile.ReadLine()) != null)
                {

                    if (line.Contains(statusIndicator))
                    {
                        indicatorLines.Add(line);
                    }
                }

                for (int i = indicatorLines.Count - 1; i >= 0; i--)
                {
                    status = AnalyzeStatus(indicatorLines[i]);
                    if (status != null)
                    {
                        break;
                    }
                }
            }
        }
        return status;
    }
}

public class NewTeamsStatus
{
    private string status;
    private TeamsLogFile teamsLogFile;

    public NewTeamsStatus()
    {
        status = null;
        teamsLogFile = null;
    }

    public void GetLogFiles()
    {
        var appdataLocal = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        var localPackagesFolder = Path.Combine(appdataLocal, "Packages");
        var teamsPackagesList = Directory.GetDirectories(localPackagesFolder, "MSTeams_*");
        string teamsLogFile = null;

        foreach (var teamsPackageFolder in teamsPackagesList)
        {
            var teamsLogFileGlob = Path.Combine(teamsPackageFolder, "LocalCache", "Microsoft", "MSTeams", "Logs");
            //var teamsPackagesLogFiles = Directory.GetFiles(teamsLogFileGlob, "MSTeams_*.log");
            var directory = new DirectoryInfo(teamsLogFileGlob);
            var teamsPackagesLogFile = directory.GetFiles("MSTeams_*.log")
             .OrderByDescending(f => f.LastWriteTime)
             .First();
            teamsLogFile = teamsPackagesLogFile.FullName;
        }
        this.teamsLogFile = new TeamsLogFile(teamsLogFile);
    }

    public void ProcessLogFiles()
    {
        if (teamsLogFile != null)
        {
            teamsLogFile = new TeamsLogFile(teamsLogFile.file);
        }

        string statusResult = null;
        if (teamsLogFile != null)
        {
            statusResult = teamsLogFile.GetStatus();
        }


        if (statusResult != null)
        {
            status = statusResult;
        }
    }

    public string GetStatus()
    {
        GetLogFiles();
        ProcessLogFiles();
        return status;
    }
}
```

Found it here https://github.com/lorentzfactr/teams_status/issues/2

**Comment by jmpkc** [comment]
Thanks for the suggestion!  I finally got time to review the NEW Teams client and the changes there.  I have added a new function/module to my app.  I'll get it uploaded soon but here is a preview of how I'm checking the New Teams status in vb.net.  I still need to fix where that MSTeams_xxxxxxxx\ folder isn't hard-coded but search for it.  Once I get that in place, I'll upload this to my base code.  Thanks!


    Private Sub subCheckTeamsNew()
        On Error Resume Next
        Dim sTeamsNewLogFolder As String = sUserProfile & "\AppData\Local\Packages\MSTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\Logs\"
        Dim searchPattern As String = "MSTeams_*.log"
        Dim files As Object = Directory.GetFiles(sTeamsNewLogFolder, searchPattern)
        Dim sTeamsNewLogFile As String = "MSTeams_xx.log"
        Dim dtLogDateTime As DateTime = "01/01/2024 01:01:01"

        For Each file As Object In files
            Dim dtFileDateTime As DateTime = FileDateTime(file)
            If dtFileDateTime > dtLogDateTime Then
                dtLogDateTime = dtFileDateTime
                sTeamsNewLogFile = file
            End If
        Next

        Dim logFileStream As New FileStream(sTeamsNewLogFile, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)
        Dim logFileReader As New StreamReader(logFileStream)
        Dim sLogLine As String
        Dim sStatusLine As String = ""

        While Not logFileReader.EndOfStream
            sLogLine = logFileReader.ReadLine()
            If InStr(sLogLine, "UserPresenceAction") Then
                sStatusLine = sLogLine
            End If
        End While

        If InStr(sStatusLine, "Available") Then
            sTeamsStatus = "Available"
            bBlinking = False
            sColor = "green"
            lblTeamsColor.BackColor = Color.Green

        ElseIf InStr(sStatusLine, "Away") Then
            sTeamsStatus = "Away"
            bBlinking = False
            sColor = "orange"
            lblTeamsColor.BackColor = Color.Black

        ElseIf InStr(sStatusLine, "OnThePhone") Then
            sTeamsStatus = "OnThePhone"
            bBlinking = True
            sColor = "red"
            lblTeamsColor.BackColor = Color.Red

        ElseIf InStr(sStatusLine, "InAMeeting") Then
            sTeamsStatus = "InAMeeting"
            bBlinking = False
            sColor = "red"
            lblTeamsColor.BackColor = Color.Red

        ElseIf InStr(sStatusLine, "DoNotDisturb") Then
            sTeamsStatus = "DoNotDisturb"
            bBlinking = True
            sColor = "red"
            lblTeamsColor.BackColor = Color.Red

        ElseIf InStr(sStatusLine, "Presenting") Then
            sTeamsStatus = "Presenting"
            bBlinking = True
            sColor = "red"
            lblTeamsColor.BackColor = Color.Red

        ElseIf InStr(sStatusLine, "Busy") Then
            sTeamsStatus = "Busy"
            bBlinking = False
            sColor = "red"
            lblTeamsColor.BackColor = Color.Red

        ElseIf InStr(sStatusLine, "Offline") Then
            sTeamsStatus = "Offline"
            bBlinking = False
            sColor = "black"
            lblTeamsColor.BackColor = Color.Black

        ElseIf InStr(sStatusLine, "BeRightBack") Then
            sTeamsStatus = "BeRightBack"
            bBlinking = True
            sColor = "purple"
            lblTeamsColor.BackColor = Color.Purple

        Else
            sTeamsStatus = sStatusLine
            bBlinking = False
            sColor = "black"
            lblTeamsColor.BackColor = Color.Black

        End If

        lblTeamsStatus.Text = sTeamsStatus
        If sColor = sColorOld And bBlinking = bBlinkingOld Then
        Else
            tmrLightControl.Enabled = True
        End If

        logFileReader = Nothing
        logFileStream = Nothing

    End Sub
